/* eslint-disable camelcase */
exports.seed = async function(knex) {
  return knex('listings').del()
    .then(() => {

      return knex('listings').insert([
        {
          title: 'Pakuan Indah Apartment',
          description: 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
          address: 'Jln. Pakuan B/239, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'Apartment',
          zip_code: 17204,
          size: 725,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 780000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Moderate Size Home in Bandung',
          description: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
          address: 'Jln. Pasir Putih D/210, Bandung, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 41812,
          size: 3670,
          number_of_bedrooms: 4,
          number_of_bathrooms: 3,
          parking_space: 2,
          valuation: 3211000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Modern Townhouse in Jakarta',
          description: 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',
          address: 'Jln. Gajah Mada C/102, Jakarta, DKI Jakarta, Indonesia',
          service_type: 'Sale',
          property_type: 'Townhouse',
          zip_code: 12849,
          size: 1320,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 1375000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Beautiful Townhose Located in the Heart Of The City',
          description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
          address: 'Jln. Surya Kencana no. 242, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'Townhouse',
          zip_code: 75232,
          size: 1620,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 1583000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Luxurious House in Bogor',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 6200000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Beautiful House in Jakarta',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'House',
          zip_code: 18924,
          size: 3000,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 3200000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Jaya Abadi Apartment',
          description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis',
          address: 'Jln. Sariwangi, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'Apartment',
          zip_code: 32851,
          size: 2495,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 780000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Unique Home in Bandung',
          description: 'Donec posuere metus vitae ipsum. Aliquam non mauris.',
          address: 'Jln. Pasir Putih D/210, Bandung, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 39402,
          size: 2042,
          number_of_bedrooms: 4,
          number_of_bathrooms: 3,
          parking_space: 2,
          valuation: 3211000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Beautiful House in Bogor',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 1024000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },

        {
          title: 'Beautiful Apartment in Bekasi',
          description: 'Beautiful and spacious apartment located in Bekasi',
          address: 'Jln. Jendral Sudirman No.1, Bekasi, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'Apartment',
          zip_code: 17143,
          size: 4500,
          number_of_bedrooms: 4,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 8102000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Beautiful House in Bogor',
          description: 'Beautiful and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 9012900,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Beautiful House in Bogor',
          description: 'Beautiful and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 1029400,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Elegant House in Bogor',
          description: 'Elegant and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 981000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Charming House in Bogor',
          description: 'Charming and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 2394000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Deposit Received'
        },
        {
          title: 'Amazing House in Bogor',
          description: 'Amazing and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          zip_code: 18924,
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 7501000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Deposit Received'
        }
      ]);
    });
};
