/* eslint-disable camelcase */
exports.seed = async function(knex) {
  return knex('listings').del()
    .then(() => {

      return knex('listings').insert([
        {
          title: 'Incredible Home in Markham',
          description: 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
          address: 'Jln. Pakuan B/239, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'Apartment',
          postal_code: "V4K 0L2",
          size: 725,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 780000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Marvelous Property in Vaughan',
          description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
          address: 'Jln. Surya Kencana no. 242, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'Townhouse',
          postal_code: "V2K 0C2",
          size: 1620,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 1583000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Splendid House in Richmond Hill',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V3K 5P2",
          size: 3000,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 3200000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Beautiful Home in Pickering',
          description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis',
          address: 'Jln. Sariwangi, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'Apartment',
          postal_code: "V6M 2I5",
          size: 2495,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 780000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Gorgeous Property in Ajax',
          description: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
          address: 'Jln. Pasir Putih D/210, Bandung, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V6M 2T5",
          size: 3670,
          number_of_bedrooms: 4,
          number_of_bathrooms: 3,
          parking_space: 2,
          valuation: 3211000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Stunning Property in Vancouver',
          description: 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',
          address: '3800 E 1st Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'Townhouse',
          postal_code: "V7M 2B5",
          size: 1320,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 1375000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },

        {
          title: ' Magnificent Home in Montreal',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5M 2C5",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 6200000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Cozy Cottage in Halifax',
          description: 'Donec posuere metus vitae ipsum. Aliquam non mauris.',
          address: 'Jln. Pasir Putih D/210, Bandung, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V6M 2I9",
          size: 2042,
          number_of_bedrooms: 4,
          number_of_bathrooms: 3,
          parking_space: 2,
          valuation: 3211000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Lovely Home in Toronto',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
          address: '3-3700 Bathurst Street, Toronto, ON, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V6R 2C5",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 1024000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },

        {
          title: 'Gorgeous Home in Toronto',
          description: 'Beautiful and spacious apartment located in Bekasi',
          address: '2121 Yonge Street, Toronto, ON, Canada',
          service_type: 'Sale',
          property_type: 'Apartment',
          postal_code: "V2M 2H7",
          size: 4500,
          number_of_bedrooms: 4,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 8102000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Stunning House in Montreal',
          description: 'Beautiful and spacious house located in Bogor',
          address: '1400-1 Place Ville Marie, Montreal, QC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V2M 2Y3",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 9012900,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Amazing Home in Calgary',
          description: 'Beautiful and spacious house located in Bogor',
          address: 'Jln. Pajajaran Indah C/21, Bogor, Jawa Barat, Indonesia',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V8M 2N7",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 1029400,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Lovely House in Halifax',
          description: 'Elegant and spacious house located in Bogor',
          address: '302-1521 Barrington Street, Halifax, NS, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V2K 2H3",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 981000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Offer Accepted'
        },
        {
          title: 'Vancouver House for Sale',
          description: 'Charming and spacious house located in Bogor',
          address: '3400 Cambie Street, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2P9",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 2394000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Deposit Received'
        },
        {
          title: 'Vancouver Home for Sale',
          description: 'Amazing and spacious house located in Bogor',
          address: '4319 Main Street, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2P4",
          size: 5257,
          number_of_bedrooms: 5,
          number_of_bathrooms: 3,
          parking_space: 4,
          valuation: 7501000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b',
          status: 'Deposit Received'
        },
        {
          title: 'Beautiful Home in Vancouver for Sale',
          description: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
          address: '1758 W 16th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5H 2P3",
          size: 3670,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 291000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale by Owner',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
          address: '3102 W Broadway, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2T2",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with Ocean View',
          description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with Mountain View',
          description: 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
          address: '2200-700 W Georgia Street, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5N 2P9",
          size: 2922,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 252000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with City View',
          description: 'In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.',
          address: '4438 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'Apartment',
          postal_code: "V5C 2P9",
          size: 1722,
          number_of_bedrooms: 1,
          number_of_bathrooms: 1,
          parking_space: 1,
          valuation: 152000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with Garage',
          description: 'In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.',
          address: '4438 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2P7",
          size: 5985,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 2,
          valuation: 861000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with Guest House',
          description: 'Duis consequat dui nec nisi volutpat eleifend.',
          address: '2200-700 W Georgia Street, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2P0",
          size: 150959,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 261000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Vancouver Home for Sale with Private Pool',
          description: 'Pellentesque eget nunc.',
          address: '2300-1055 Dunsmuir Street, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'Apartment',
          postal_code: "V5C 2B9",
          size: 590,
          number_of_bedrooms: 1,
          number_of_bathrooms: 1,
          parking_space: 0,
          valuation: 25000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62a915d40fb854efec56620b'
        },
        {
          title: 'Cozy Home for Sale in Vancouver',
          description: 'In sagittis dui vel nisl.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Beautiful Home for Sale in Vancouver',
          description: 'Duis aliquam convallis nunc.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Charming Home for Sale in Vancouver',
          description: 'Phasellus in felis.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Nice Home for Sale in Vancouver',
          description: 'Nulla ut erat id mauris vulputate elementum.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Beautiful House for Sale in Vancouver',
          description: 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Vancouver House for Sale',
          description: 'Duis consequat dui nec nisi volutpat eleifend.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Vancouver Home for Sale',
          description: 'Nullam sit amet turpis elementum ligula vehicula consequat.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493',
        },
        {
          title: 'Modern Home for Sale in Vancouver',
          description: 'Aenean fermentum.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Coquitlam Home for Sale with Ocean View',
          description: 'Cras in purus eu magna vulputate luctus.',
          address: '3747 W 10th Avenue, Coquitlam, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Burnaby Home for Sale with Ocean View',
          description: 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
          address: '3747 W 10th Avenue, Burnaby, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Richmond Home for Sale with Ocean View',
          description: 'Aenean fermentum.',
          address: '3747 W 10th Avenue, Richmond, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Surrey Home for Sale with Ocean View',
          description: 'Nulla justo.',
          address: '3747 W 10th Avenue, Surrey, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Beautiful Home in the Heart of Vancouver',
          description: 'Nulla ut erat id mauris vulputate elementum.',
          address: '4602 W Broadway, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5Z 1G9",
          size: 2522,
          number_of_bedrooms: 4,
          number_of_bathrooms: 2,
          parking_space: 2,
          valuation: 325000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Penthouse Suite in Vancouver',
          description: 'Nullam porttitor lacus at turpis.',
          address: '1508 W Georgia Street, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'Condo',
          postal_code: "V6G 2T3",
          size: 1822,
          number_of_bedrooms: 2,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 285000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Luxury Home in Vancouver Suburbs',
          description: 'Donec dapibus.',
          address: '6411 Nelson Avenue, Burnaby, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5H 4H4",
          size: 3122,
          number_of_bedrooms: 5,
          number_of_bathrooms: 4,
          parking_space: 2,
          valuation: 485000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Cozy Home Close to UBC',
          description: ' Duis consequat dui nec nisi volutpat eleifend.',
          address: '5668 University Boulevard, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V6T 1K6",
          size: 2122,
          number_of_bedrooms: 3,
          number_of_bathrooms: 2,
          parking_space: 1,
          valuation: 220000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Newly Renovated Home in Downtown Toronto',
          description: 'Nullam sit amet turpis elementum ligula vehicula consequat.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: 'Beautiful Home in the Suburbs of Montreal',
          description: 'Vestibulum ac est lacinia nisi venenatis tristique.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Lease',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        },
        {
          title: ' Charmng Home in the Heart of Ottawa',
          description: 'Fusce consequat.',
          address: '3747 W 10th Avenue, Vancouver, BC, Canada',
          service_type: 'Sale',
          property_type: 'House',
          postal_code: "V5C 2E9",
          size: 4222,
          number_of_bedrooms: 3,
          number_of_bathrooms: 3,
          parking_space: 3,
          valuation: 392000000,
          organization_id: 'org_SdeKNTPqOTyZc27v',
          agent_id: 'auth0|62badd1761165c6696257493'
        }







       
      ]);
    });
};