const COMMENTS = 'COMMENTS';
const FILES = 'FILES';
const TASKS = 'TASKS';
const PHOTO = 'PHOTO';
const TRANSACTIONS = 'TRANSACTIONS';


export {
  COMMENTS,
  TRANSACTIONS,
  FILES,
  TASKS,
  PHOTO,
};